# Generated by Django 4.2.3 on 2023-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.DateField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
