# Generated by Django 4.2.3 on 2023-07-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_title_ingredient_food_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
